### ISSUE TITLE
Base resupply box heal function not working

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#10]
**Description:**
The ACE interact & Scrollwheel option to heal is not functioning.

**Steps to reproduce:**
Take damage
Go to box
Attempt to heal, nothing happens

**Expected behavior:**
Player should reset to full health

**Where did the issue occur?**
- In-Game

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by davidcit646** [comment]
cScripts update fixed many of the ace medical issues. Will move to In Progress
