### ISSUE TITLE
Hunter slots don't have vehicle permissions

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#103]
**Description:**
Hunter infantry group don't appear to have vic perms

**Steps to reproduce:**
- Join HUNTER
- Attempt to get into air vic

**Expected behavior:**
HUNTER should have the same permissions as GUNSLINGER

**Where did the issue occur?**
- In-Game

**Additional context:**
Related to #58 

**Screenshots:**
N/A

**Comment by davidcit646** [comment]
Fixed in latest round of bug fixes.
