### ISSUE TITLE
Slot screen label 

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#108]
**Description:**
1. Spelling mistake (Infidel - Infadel)
2. Missing BUFFALO-2 slot name
3. Sparrow 1 labeled Raven

**Steps to reproduce:**
log on

**Expected behavior / Requested Solution:**

**Where did the issue occur?**
- Lobby

**Additional context:**

**Screenshots:**

**Comment by Jaidendude** [comment]
2 related to #20 

3 is non-issue, proper callsign in 1stBAT Sig chart is Raven

**Comment by Jaidendude** [comment]
@davidcit646 After deliberating with a pub, callsign for armed littlebird should be changed to Sparrow instead of raven to avoid issues

**Comment by davidcit646** [comment]
Fixed in latest round of bug fixes.
