### ISSUE TITLE
Fortify Tool usage

### ISSUE THREAD

**Issue by Smiggus** [7CavArma3Dev/7Cav-Alive-Altis#109]
**What map is this feature request for?**
Altis

**Is your feature request related to a problem? Please describe.**
Not sure if intended but troopers are unable to use the fortify tool on the server.

**Describe the solution you'd like**
Enabled and constrained w/budget for fortify tool for Apollo and Mission Controller units

**Describe alternatives you've considered**
Pre-fabs are good but theyre very zeus dependent.

**Additional context**
CPL.Curtis.J has raised this issue.

**Comment by davidcit646** [comment]
Unintended consequence of merging shit without sifting through it first. 

Elevated priority. This is next on the list.

**Comment by 7cavZlobinN** [comment]
Fixed #153
