### ISSUE TITLE
ACE Sitting

### ISSUE THREAD

**Issue by Smiggus** [7CavArma3Dev/7Cav-Alive-Altis#112]
**What map is this feature request for?**
All Alive Maps

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Placing of ACE Sitting Modules in Mission

**Describe alternatives you've considered**
Not sitting is not an option.

**Additional context**
ACEX Sitting Module in Eden Editor

**Comment by AndreasBrostrom** [comment]
Should be active in cScripts CBA_Settings. 
The moduel system of ace is more or less depricated.

**Comment by davidcit646** [comment]
Fixed in latest round of bug fixes.
