### ISSUE TITLE
INFIDEL wrong ingame map marking

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#115]
**Description:**
Upon entering the game INFIDEL gets assigned the standard callsign Alpha 2-3

**Steps to reproduce:**
- Go to … In game
- Click ...
- See ...

**Expected behavior / Requested Solution:**
Expected it to say INFIDEL 1 on map

**Where did the issue occur?**
In game

**Additional context:**

**Screenshots:**

**Comment by vaughn-v** [comment]
also on the slot screen you have it spelled INFADEL instead of INFIDEL @davidcit646

**Comment by davidcit646** [comment]
Fixed in latest round of bug fixes.
