### ISSUE TITLE
RPT Errors - 1/28/2020

### ISSUE THREAD

**Issue by uaon** [7CavArma3Dev/7Cav-Alive-Altis#116]
**Issue:**
Errors shown on the new RPT.log file for the problems that occurred on 1/28/2020,

**Base Class, Missing / Invalid:**
`   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_AutomaticRifleman_F/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_RiflemanLAT_F/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_Rifleman_F/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_FireTeamLeader_F/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_Grenadier_F/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_SquadLeader_F/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_Marksman_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_AAT_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_AT_Local/
   Cannot find base Cav_B_Charlie_base_F 
 description.ext/CfgLoadouts/Cav_B_C_Support_MK19_TeamLeader_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_Support_MK19_Gunner_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_Support_MK19_Assistant_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/CAV_Charlie_Machinegunner_TeamLeader_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/CAV_Charlie_Machinegunner_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_Support_Mortar_AutomaticRifleman_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_Support_Mortar_TeamLeader_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_Support_Mortar_Gunner_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_Support_Mortar_SquadLeader_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_AAA_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_AA_Local/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/CAV_Charlie_TOWSFTL/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/CAV_Charlie_TOWSGUN/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/CAV_Charlie_TOWSTRI/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_Officer_F/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_PlatoonMedic_F/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/CAV_Charlie_CompanyStaff_F/
   Cannot find base Cav_B_Charlie_base_F  description.ext/CfgLoadouts/Cav_B_C_CombatLifeSaver_F/`

**Description.ext**
`
Mission 7Cav_FullSpectrum_v5.1.2.Altis: Number of roles (91) is different from 'description.ext::Header::maxPlayer' (60)`

**USAF Mod:**
`
Error in expression <(ammo3<=62)>
Error position: <ammo3<=62)>
Error Undefined variable in expression: ammo3
unable to compile MFD condition '(ammo3<=62)'
`

`
unable to compile MFD condition '0 * (1-(((pylonSelected15 + pylonAmmoRelative15 > 1) + (pylonSelected16 + pylonAmmoRelative16 > 1)+(pylonSelected17 + pylonAmmoRelative17 > 1)+(pylonSelected18 + pylonAmmoRelative18 > 1)+(pylonSelected19 + pylonAmmoRelative19 > 1))))'
Error in expression <elected14 + pylonAmmoRelative14 > 1) + (pylonSelected20 + pylonAmmoRelative20 > >
Error position: <pylonSelected20 + pylonAmmoRelative20 > >
Error +: Undefined variable in expression: pylonselected20
unable to compile MFD condition '0 * ((pylonSelected11 + pylonAmmoRelative11 > 1) + (pylonSelected12 + pylonAmmoRelative12 > 1) + (pylonSelected13 + pylonAmmoRelative13 > 1) + (pylonSelected14 + pylonAmmoRelative14 > 1) + (pylonSelected20 + pylonAmmoRelative20 > 1))'
`

**Base Error:**
`
Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
a3_characters_f
`

**Comment by AndreasBrostrom** [comment]
can be ignored
```Description.ext
Mission 7Cav_FullSpectrum_v5.1.2.Altis: Number of roles (91) is different from 'description.ext::Header::maxPlayer' (60)
```

**Comment by AndreasBrostrom** [comment]
missing classnames is fixed with this:
https://github.com/7Cav/7Cav-Alive-Altis/pull/113/files

**Comment by AndreasBrostrom** [comment]
```
Base Error:
Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted. a3_characters_f
```
remove the character uses and perge the mod list inside of mission.sqm

**Comment by davidcit646** [comment]
> Description.ext
Mission 7Cav_FullSpectrum_v5.1.2.Altis: Number of roles (91) is different from 'description.ext::Header::maxPlayer' (60)

Fixed in next update.

>description.ext/CfgLoadouts/Cav_B_C_Support_Mortar_SquadLeader_Local/ Cannot find base

not sure what's causing this. Everything looks just fine, not too sure what's going on here. :thonk:

**Comment by AndreasBrostrom** [comment]
see my comments. 
you have not included any cav classnames.
