### ISSUE TITLE
ACE3 RCO (PIP) FPS Bug

### ISSUE THREAD

**Issue by Prototype9x** [7CavArma3Dev/7Cav-Alive-Altis#117]
**Description:**
ACE3 RCO (PIP) Scope creates a massive FPS drop/Stuttering when put on weapon.

**Steps to reproduce:**
- Go to Arsenal > Equip ACE3's RCO (PIP) Scope on to weapon > Close Arsenal.
- See massive FPS drop/Stuttering while stationary/moving.

**Expected behavior:**
FPS should not drop so aggresively. 

**Where did the issue occur?**
- In-Game

**Additional context:**
ACE3's RCO (2D) works fine.

**Screenshots:**

Notice FPS at bottom left with RCO (PIP) attached vs with scope removed.

![20200129115927_1](https://user-images.githubusercontent.com/56491899/73378630-e00da000-428e-11ea-9c0e-07a7b1f491c5.jpg)

![20200129120202_1](https://user-images.githubusercontent.com/56491899/73378796-31b62a80-428f-11ea-8bf8-32be2d60d5ff.jpg)

**Comment by Prototype9x** [comment]
FPS counter did not port over with screenshot. Top photo was at 10FPS. Bottom photo was at 70FPS.

**Comment by Jaidendude** [comment]
@Prototype9x What mods are you running? Does this issue continue to happen in singleplayer, I.E. ACE Arsenal?

Does this issue persist with only ACE3 running?

**Comment by Prototype9x** [comment]
All of Tact2 Mods + Achilles 

It happens in Singleplayer (Eden Editor) with ACE3 running.

It does not happen with ACE3 unloaded. The optic is a part of ACE3.

**Comment by Jaidendude** [comment]
> It happens in Singleplayer (Eden Editor) with ACE3 running.

If this happens in singleplayer it isn't an issue related to the mission file and we will not be able to fix it. 

PIP Scopes cause your game to render a FPS view of what you're looking at at the same time as your zoomed view. Use a 2D scope instead.

**Comment by Prototype9x** [comment]
Thank you girl your time.

**Comment by Prototype9x** [comment]
For*
