### ISSUE TITLE
Remove RCO (PIP) Scope 

### ISSUE THREAD

**Issue by Prototype9x** [7CavArma3Dev/7Cav-Alive-Altis#118]
**What map is this feature request for?**
Altis

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

See Issue #117  

**Describe the solution you'd like**

Blacklist RCO (PIP) from arsenal until it is Fixed.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Jaidendude** [comment]
This isn't a bug and won't be fixed.
