### ISSUE TITLE
Increase mustang slots or add Mustang-2

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#13]
**What map is this feature request for?**
Ex. Altis

**Is your feature request related to a problem? Please describe.**
Only 4(5) slots available to mustang, on a full server on WFW this will more than likely present an issue if mustang is sticking together cohesively

**Describe the solution you'd like**
Increase Mustang-1 slots, or ideally add in Mustang-2

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by davidcit646** [comment]
Low priority at this time, will add at a later date.
