### ISSUE TITLE
USAF Testing 

### ISSUE THREAD

**Issue by Smiggus** [7CavArma3Dev/7Cav-Alive-Altis#131]
4 Hour, 48 Hour and 72 Hour server testing. Monitor for crashes and logs. Need a flag system for errors.
- Simple fix system would be upload two RPTs to Github from varying tests, for change tracking to said logs.

**Comment by Smiggus** [comment]
Pending comment from Cit. Issue is related to the Cavpack Rebuild scheduled.

**Comment by davidcit646** [comment]
Do you want the individual mission files? Right now I have the following currently on the dev server:

1. Public Cav Addon
2. 7thCavFactPack
3. RHS
4. Vanilla

**Comment by Smiggus** [comment]
On my own test bench, I have the full cav training modset, is the above set what you would prefer me to test on?  Either way that server is up 24/7, with a beta build for the previous tac-2 Altis (which was around the time we were adding blacklists recently), the server seemed fine. Keep in mind significantly reduced load, but the server was up. Was thinking to redo this test, with a client connected to it and see how it fares.

Rpts attached in zip file. 
[Archive.zip](https://github.com/7Cav/7Cav-Alive/files/4203309/Archive.zip)

**Comment by davidcit646** [comment]
Is this with the 7th Cav Community Addon factions?

**Comment by Smiggus** [comment]
Yep, that is with the full complement of our tac 2 mods I believe
