### ISSUE TITLE
MP Commands 

### ISSUE THREAD

**Issue by davidcit646** [7CavArma3Dev/7Cav-Alive-Altis#147]
**Description:**
!MP commands to warn/give rules to players.

**Steps to reproduce:**
- type !mp in chat

**Expected behavior:**
Various MP commands that warn, kick, and display rules to player

**Comment by davidcit646** [comment]
Requested by the MP department

**Comment by BojanOnTheInternet** [comment]
While those commands _may_ be needed for Tac1, I can't imagine the last time I've seen an MP need to use such commands on Tac2. As such, I won't be wasting my time developing features that are never used.
