### ISSUE TITLE
Tow the Howitzer

### ISSUE THREAD

**Issue by Smiggus** [7CavArma3Dev/7Cav-Alive-Altis#148]
**What map is this feature request for?**
All

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
https://www.youtube.com/watch?v=hsbWsLg5CMg

**Describe alternatives you've considered**
Not towing is ok too

**Additional context**
Would be a nice to have, might drive up Apollo/Havoc players

**Comment by Jaidendude** [comment]
resolved by #191
