### ISSUE TITLE
Zeus request to be able to pause Alive for MCCs 

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#155]
**What map is this feature request for?**
All

**Is your feature request related to a problem? Please describe.**
feedback from Zeuses suggest Alive strength and reinforcements may make some MCCs too difficult to control and account for.

**Describe the solution you'd like**
Don't know if this is possible 

**Describe alternatives you've considered**
Current solution is manual deletion of forces and qrf, sometimes to the detriment of mcc

**Additional context**
This seems like a longer term issue, but wanted to document a Zeus request

**Comment by Jaidendude** [comment]
Not sure if this is possible

**Comment by uaon** [comment]
http://alivemod.com/wiki/index.php/Military_AI_Commander#Editor_Notes

- Halting OPCOM activity
The AI Commander can be stopped and started by syncing a trigger to the module. When all trigger states are TRUE, the Commander will commence attacking the next unsecured objective. If the trigger state returns to False, the Commander will complete any currently assigned objectives then stop. For example, this can be used to stop AI Commander if no players are present on the map.

**Comment by davidcit646** [comment]
Good find! We'll need to mess around with this in closed testing to figure out how we can best implement this.
