### ISSUE TITLE
ACE Medical Stitch broken by update

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#157]
**Description:**
After the update today, full medical perms Mustang does not get the option to stitch wounds. 

Unclear if the bandages now fully fix wounds or no-one can stitch.

**Steps to reproduce:**
Check any wound as a Mustang role on Tac 2

**Expected behavior:**
Stitch Option appears

**Where did the issue occur?**
Tac 2 Alive In-Game

**Additional context:**
ACE update probably broke it 

**Screenshots:**

**Comment by Jaidendude** [comment]
Might be a CBA settings issue

**Comment by OceanMan1125** [comment]
Relay from Cit:

Advanced Bandages - Enable, can reopen 

@davidcit646

**Comment by davidcit646** [comment]
Fixed in latest update
