### ISSUE TITLE
F35 Ordinance isn't working

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#16]
**Description:**
SDB IIs, AIM-120Cs disappear after launch

**Steps to reproduce:**
Get in an F-35
Load up said ordinance
Attempt to fire
Nothing happens

**Expected behavior:**
Ordinance should act as expected

**Where did the issue occur?**
- In-Game

**Additional context:**
Ammo counter in the top right goes down, but no visual/audio feedback is given, missile/bomb does not function

**Screenshots:**
N/A

**Comment by davidcit646** [comment]
They need to double click on "Loadout" and it will instantly replenish their ammunition supply. Untested, please verify.
