### ISSUE TITLE
Vehicle Perms for Viking

### ISSUE THREAD

**Issue by VinoEtCaseus** [7CavArma3Dev/7Cav-Alive-Altis#161]
**Description:**
Players slotted in Viking cannot enter base vehicles. 

**Steps to reproduce:**
1. Slot under Viking
2. Try to enter vehicles at base

**Expected behavior:**
Will show vehicle perm error message

**Where did the issue occur?**
In-Game

**Additional context:**
Only tested with Viking-1 TL

**Comment by davidcit646** [comment]
Infantry classnames for Viking are `rhsusf_army_ocp_rifleman` and the permissions are applied to `rhsusf_army_ocp_arb_rifleman`. Changed classnames to reflect this discrepancy.

**Comment by davidcit646** [comment]
Confirmed working.

**Comment by Jaidendude** [comment]
Issue still present on takistan
