### ISSUE TITLE
Slotting screen fixes

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#166]
**Description:**

1. Altis&Tanoa:
Buffalo 2 names in the slot screen are not under Buff 2 call-sign (Alpha 2-9 instead) . Secondary, pilot/copilot are backwards. See screenshot 1.

2. Altis: 
Double AH-6 slots. (Sparrow and Raven). See screenshot 2.

3. Tanoa: 
Slots for base AA defenses. See screenshot 3.

**Steps to reproduce:**
Log in to Tac 2
Check slot screen

**Expected behavior:**
1. BUFFALO-2 element
Pilot
Co-Pilot

2. Single AH-6 unit

3. No Spartan Slots

**Where did the issue occur?**
- Lobby (Both Altis and Tanoa)

**Additional context:**
non critical

**Screenshots:**

![Screenshot_1](https://user-images.githubusercontent.com/61951971/76375665-ac6e6d00-6346-11ea-9b33-eecb92e7c73e.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/61951971/76375666-ac6e6d00-6346-11ea-8c4f-9ef0a86880a9.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/61951971/76375663-abd5d680-6346-11ea-84a6-b80e0c436504.jpg)

**Comment by davidcit646** [comment]
Fixed on Tanoa; merging changes to Altis;
Fixed on Altis; merging changes to WFW;
Fixed on WFW; all maps completed; moving to done;

**Comment by Jaidendude** [comment]
Merged
