### ISSUE TITLE
Vehicle Rearm point turrets de-spawn (Tanoa)

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#167]
**Description:**
The movable static turrets (M2, TOW, ...) near the vehicle-rearm point de-spawn from vehicle inventory after a minute and appear back at point.

Side effect of this is that the vehicle garage cover disappears with the turret re-spawn

**Steps to reproduce:**
Load turret in vic
Wait 1 min

**Expected behavior:**
Static weapon remain in the vehicle.

**Where did the issue occur?**
Tanoa in-game

**Additional context:**

**Screenshots:**

**Comment by 7cavZlobinN** [comment]
Same bug as #158 , fixed in #165 for both tanoa and altis

**Comment by davidcit646** [comment]
@7cavZlobinN moved to Quality assurance for testing.
