### ISSUE TITLE
Tanoa Map markers

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#169]
**Description:**

1. 2 map shapes (maybe triggers) present. One red rectangle over 3/4 of map and dark marker over 1/5 of map. See screenshot 1

2. Fob Name Adjusted from Cold Blood to Coldblud. (Reference CSM Coldblud medalhttps://wiki.7cav.us/index.php/Awards_and_Decorations ) 

**Steps to reproduce:**
Check Map

**Expected behavior:**

**Where did the issue occur?**
- Map-Screen

**Additional context:**

**Screenshots:**
![screenshot1](https://user-images.githubusercontent.com/61951971/76380054-180a0780-6352-11ea-8ebd-c33ee876338a.jpg)

**Comment by Jaidendude** [comment]
merged
