### ISSUE TITLE
Opening service menu causes issues

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#17]
**Description:**
Occasionally opening the service menu in the F35 causes issues

**Steps to reproduce:**
Unknown at this time

*Expected behavior:**
N/A

**Where did the issue occur?**
In-game

**Additional context:**
Reported by Cosme, he exploded when opening the service menu once

**Screenshots:**
N/A

**Comment by davidcit646** [comment]
Need more information. Possibly a USAF mod problem? Will space out planes more and see if this fixes the problem.

**Comment by Jaidendude** [comment]
USAF going to be removed from TAC2, closed.
