### ISSUE TITLE
Tanoa Fortify vehicle binding

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#170]
**Description:**
The fortify mechanic is currently bound to the AUV Deploy vehicle, rather than the empty SOV tuck. Posting here because I was told this may be backwards.

**Steps to reproduce:**
Check fortify abilities and intended vehicles

**Expected behavior:**
Unaware which is the intended vehicle

**Where did the issue occur?**
- Tanoa In-Game 

**Additional context:**

**Screenshots:**

**Comment by Jaidendude** [comment]
When I designed the Tanoa COIN map the AUV Deploy was a straight upgrade to the SOV vehicle, so it made sense to me.
