### ISSUE TITLE
Change Gunslinger to Misfit elements for Warfare Wednesday

### ISSUE THREAD

**Issue by Smiggus** [7CavArma3Dev/7Cav-Alive-Altis#171]
**What map is this feature request for?**
Warfare Wednesday map.

**Is your feature request related to a problem? Please describe.**
Always frustrated when ya boy can't get his SL spot. So asking for the change to make it my billeted position.

**Describe the solution you'd like**
Change GUNSLINGER callsign to MISFIT

**Describe alternatives you've considered**
N/A, no alternatives.

**Additional context**

**Comment by Jaidendude** [comment]
Merged
