### ISSUE TITLE
IED request

### ISSUE THREAD

**Issue by millertime505** [7CavArma3Dev/7Cav-Alive-Altis#175]
**What map is this feature request for?**
Takistan

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see IED's used. If you want to maintain gameplay for everyone just set it a small area and mark it on map. 

**Describe alternatives you've considered**
Wait till zues gets on

**Additional context**
no

**Comment by davidcit646** [comment]
Added civilians to Takistan; pending player approval, will experiment with IED implementation in future updates.

**Comment by Jaidendude** [comment]
IEDs should only be used with asymmetrical style AI Commanders, it's possible to use them with regular conventional mode, but then you get a flat distribution across the entire map, rather than integrated tasks (AI have to physically visit the location to plant them)
