### ISSUE TITLE
A-10C Service Menu

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#179]
**Description:**
The A-10 is having issues allowing loadouts to properly be configured in the service menu.

**Steps to reproduce:**
When in the service menu, clicking loadout and attempting to change any of the pylons results in nothing. 

**Expected behavior / Requested Solution:**
Should allow full customization of loadouts through service menu

**Where did the issue occur?**
in game, at base

**Comment by davidcit646** [comment]
Question: Which map does this occur on?

**Comment by Jaidendude** [comment]
could be related to #17
