### ISSUE TITLE
Add adjustable budget for ACE Fortify

### ISSUE THREAD

**Issue by uaon** [7CavArma3Dev/7Cav-Alive-Altis#184]
**What map is this feature request for?**
Adjustable Budget for ACE Fortify  (ALL Maps)

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Allow budget to be set via module or via action like old tact 2 mission... (chat monitoing for mc "param0" "param1" "param2" ...etc)

**Describe alternatives you've considered**
Currently the fortify option is hard set by the fortifyinit.sqf script

`_items = [
  ["Land_HBarrier_1_F", 2],
  ["Land_HBarrier_5_F", 5],
  ["Land_HBarrierWall4_F", 10],
  ["Land_HBarrierWall_corner_F", 10],
  ["Land_HBarrierTower_F", 25],
  ["Land_BagFence_Long_F", 5],
  ["Land_BagBunker_Small_F", 25],
  ["Land_BagBunker_Large_F", 50],
  ["Land_CncBarrierMedium_F", 5],
  ["Land_HelipadCircle_F", 25],
  ["Land_PortableLight_double_F", 1],
  ["StorageBladder_01_fuel_forest_F", 175],
  ["ClutterCutter_EP1", 0]
];
[west, 800, _items] call acex_fortify_fnc_registerObjects;`

Now you can just do a copy paste into server exec and just change the budget to a higher value.. e.g,
`[west, 99999, _items] call acex_fortify_fnc_registerObjects;`
But that is a bit hacky and not really manageable... probably borderline abusive.

What I'm thinking is have a variable that is set for it like `FortifyPoints` and have that either adjustable via mc slots like a add action where it adds 100$ to budget on a laptop or something, 

Or have a Achillies module that allows you to have a single line box to input the new value and exec.

Or just add the chat monitoring and do all that fun RSC_TEXT and dik codes with the mc parameters in sidechat.

**Additional context**
N/A

**Comment by BojanOnTheInternet** [comment]
Fixed with https://github.com/7Cav/7Cav-Alive/pull/258
