### ISSUE TITLE
Raven is accidentally given a default listing at the lobby screen (Alpha 2-2, etc)

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#20]
**Description:**
Raven does not have the correct header for the slots on the lobby screen

**Steps to reproduce:**
Join the server
See the slot above sparrow

**Expected behavior:**
N/A

**Where did the issue occur?**
- Lobby

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by davidcit646** [comment]
Screenshot? 

We do not appear to have a Raven at this time, it appears as if the only Littlebird asset is Sparrow

**Comment by Jaidendude** [comment]
@davidcit646 As requested [Lobby issue](https://i.gyazo.com/70317c0d51a7eb94ead47c85e5defbd9.png)

[According to the Battalion signals sheet, Littlebirds fall under the callsign of Raven.](https://i.gyazo.com/5f329e622f21a6513090d9bddc5a2ebd.png)

**Comment by davidcit646** [comment]
Roger, will change to Raven
