### ISSUE TITLE
add mission developer slot to all missions

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#209]
**What map is this feature request for?**
All maps

**Is your feature request related to a problem? Please describe.**
Mission developers do not have a reserve slot, and no access to zeus if needed.

Add slots to lobby screens for mission developers

**Comment by BojanOnTheInternet** [comment]
Mission developers that need Zeus access should be in contact with S6 to have the developer role set for them (DD) which will grant them Zeus access regardless of their slot. That said, people that are only peripherally involved with mission development shouldn't need Zeus 24/7, and if there is some exception can login as admin and do things like that.
