### ISSUE TITLE
Helo Pilots unable to repair aircraft. PERMISSIONS

### ISSUE THREAD

**Issue by Smiggus** [7CavArma3Dev/7Cav-Alive-Altis#212]
**Description:**
Pilot Alpha 2-6, 2LT Maclure @6:55PM EST on 03/23/2020

**Steps to reproduce:**
- Damange Aircraft
- Attempt to repair with tool kit

**Expected behavior:**
Ace interact repair option

**Where did the issue occur?**
In-Game

**Additional context:**
Pilot engineer permissions

**Screenshots:**

**Comment by Jaidendude** [comment]
Perhaps related to #208
