### ISSUE TITLE
Member Already Defined Error in rpt log

### ISSUE THREAD

**Issue by uaon** [7CavArma3Dev/7Cav-Alive-Altis#213]
**Description:**
3/24/2020 20:00 Zulu
Getting the following inside the rpt logs

ErrorMessage: File mpmissions\__cur_mp.Altis\mission.sqm, line 41481: /Mission/Entities/Item0/Entities/Item3/Entities.Item145: Member already defined.

**Steps to reproduce:**
End the mission via Zeus, or via Objectives
**Expected behavior:**
Should switch to next map cycle without crashing server.

**Where did the issue occur?**
RPT.log
Server Crash dump

**Additional context:**
This "seems" to be causing the server to hiccup when reloading the map. Instances was on the Takistan map before it went to debriefing and following that the server dies.

Not sure how arma handles map switching and why its showing a tmp path for _cur_mp.altis/ for the mission instead of using the takistan map.
**Screenshots:**
N/A

**Comment by davidcit646** [comment]
Known issue, not sure what happened; investigating. 
Possibly a faulty merge.

**Comment by BojanOnTheInternet** [comment]
Altis was broken, and was rolled back.
