### ISSUE TITLE
Alive generates lag-inducing numbers of AI for Rasman, Shukurkalay, and Chaman (TAKISTAN)

### ISSUE THREAD

**Issue by JoyfulJP** [7CavArma3Dev/7Cav-Alive-Altis#216]
**Description:**
When attacking Rasman (Air Comm), around 9-10 helicopters are spawned in Chaman and fly to reinforce Rasman with Air Assault ISIS. When attacking Shukurkalay, Alive spawns 8-9 Platoons of infantry on Chaman to reinforce the city. This is lag inducing.

**Steps to reproduce:**
- Go to Rasman or Shukurkalay. Have players operate there
- Observe

**Expected behavior:**
Platoons of infantry will spawn or Helicopters will spawn en masse. (typically CSAT due to default unit)

**Where did the issue occur?**
- In Game

**Additional context:**
Extremely lag inducing- activates multiple AO's when attempting to reinforce Rasman. Floods server with infantry when elements danger close to Chaman.

**Screenshots:**
N/A

**Comment by davidcit646** [comment]
@OceanMan1125 Remedy this ASAP. I recommend performing localized testing, and making adjustments where necessary. Let me or @MacMillan-M if you need any assistance.

**Comment by davidcit646** [comment]
@MacMillan-M Get on this. I want this fixed for next mission release. If you need help let me know I'll be glad to help where possible.

**Comment by Jaidendude** [comment]
Happened today, like 7 taru helis spawned in, shouldn't be happening
