### ISSUE TITLE
Loyalty box ROE

### ISSUE THREAD

**Issue by MacoD1** [7CavArma3Dev/7Cav-Alive-Altis#219]
**What map is this feature request for?**
all Maps

**Is your feature request related to a problem? Please describe.**
There is no ROE for the loyalty box feature. People are allowed to fly in helicopters without being in a pilot slot yet. If this is allowed why are pilot seats locked. If you was to spawn a tank from loyalty box you would not be able to get into it unless being in a sabre slot, I feel the same should apply to all airframes.

**Describe the solution you'd like**
If free use of loyalty box items are to happen then the items spawned should be fully unlocked and the arma 3 tac 2 ROE to updated to include the rules on how the loyalty box is to be used for ease of understanding for all public and cav member players

**Describe alternatives you've considered**
None available. 

**Additional context**

**Comment by davidcit646** [comment]
If you spawn it using the loyalty points system then you can use it without being in a slot. It's technically yours cause you worked for it. But if you wish to use an asset that's already there then you need to slot in to use it.

There's currently no ROE that specifically states you need to be in a specific slot to use a specific thing, we just added permissions to prevent people from using things they ought not to.

If someone wants to spawn a uh and use It as a taxi to the ao and discard it when they hry there, it's their money they can do whatever they want. But if they do that with the actual Buffalo, then that's a problem because it's locked to the pilots, so when they go to use it, itll be gone

**Comment by Jaidendude** [comment]
One of the problems that the loyalty spawn presents is if a player wants to drive a tank, then an airframe, they would have to swap slots to do so, with the potential of not being able to slot into a pilot slot to fly a loyalty spawned airframe.

Basically, remove permissions for loyalty spawned vehicles

**Comment by davidcit646** [comment]
I was told you didn't need to even reslot, that you were able to get into it regardless?

**Comment by Jaidendude** [comment]
No you can't get into loyalty spawned vics if you don't have the slot

**Comment by davidcit646** [comment]
I see what the problem is, then. Keep this pinned, we'll work on this over time.

**Comment by MacoD1** [comment]
If something can be added into ROE to fully explain the purpose of the loyalty box that would be great. The writing of must be in said slot for said vic must be taken away on the item that is being spawned if all loyalty items will be fully unlocked. Becasue its gives off the look of well if only someone in the slot can use this then it must be that you should be in that slot to use it. That is where the issue came from.

**Comment by MacoD1** [comment]
> If you spawn it using the loyalty points system then you can use it without being in a slot. It's technically yours cause you worked for it. But if you wish to use an asset that's already there then you need to slot in to use it.
> 
> There's currently no ROE that specifically states you need to be in a specific slot to use a specific thing, we just added permissions to prevent people from using things they ought not to.
> 
> If someone wants to spawn a uh and use It as a taxi to the ao and discard it when they hry there, it's their money they can do whatever they want. But if they do that with the actual Buffalo, then that's a problem because it's locked to the pilots, so when they go to use it, itll be gone

In a way there is a rule if not in the ROE. Because it states on the item in the loyalty box that for example a tank or Helo that you must be in either Sabre or Buffalo slot to drive/fly. So maybe a higher look at that so as not to step on the original idea of the loyalty box and purpose.

**Comment by BojanOnTheInternet** [comment]
The origin intention with the loyalty rewards was that vehicle permissions apply to them as well, as vehicle permissions are a way to limit the numbers of various types of assets in an AO. If you are able to spawn vehicles and the permissions are not being applied to them, then the permissions have likely not been configured for that vehicle.

**Comment by BojanOnTheInternet** [comment]
Are we happy with keep this as is?
