### ISSUE TITLE
Scrollwheel heal on arsenal is not working

### ISSUE THREAD

**Issue by longlostblake** [7CavArma3Dev/7Cav-Alive-Altis#24]
**Description:**
Scroll wheel Heal does not work on the arsenal crates.

**Steps to reproduce:**
- Go to ingame to an arsenal and scroll wheel to heal when wounded
- No change to health

**Expected behavior:**
Should heal you back to full health

**Where did the issue occur?**
In-Game

**Additional context:**
n/a

**Screenshots:**
n/a

**Comment by Jaidendude** [comment]
Identical to #10
