### ISSUE TITLE
WIKI UPDATE

### ISSUE THREAD

**Issue by davidcit646** [7CavArma3Dev/7Cav-Alive-Altis#247]
ACE Heal function
`
call { this addaction [
"<t color='#AF507B'>Full Heal</t>", 
{player call ace_medical_treatment_fnc_fullHealLocal},
[],
1.5,
true,
true,
"",
"true",
5,
false,
"",
""
];
}
`

addAction function 
`
ASDF
`

**Comment by BojanOnTheInternet** [comment]
Cool.
