### ISSUE TITLE
ALiVE Unit Spawn Issue

### ISSUE THREAD

**Issue by mcurrier25** [7CavArma3Dev/7Cav-Alive-Altis#248]
**Description:**
The map of Takistan is spawning in CSAT forces along with ISIS however the ratio of CSAT and ISIS is 10:1.

**Steps to reproduce:**
- Go to mission select
- Click Takistan (Newest Version)
- See troops spawning that arent of the correct faction

**Expected behavior:**
N/A

**Where did the issue occur?**
- In-Game 

**Additional context:**
N/A

**Screenshots:**
N/A.

**Comment by Jaidendude** [comment]
Please present screenshots or a grid location of the hostiles

**Comment by davidcit646** [comment]
Screenshots provided:
https://cdn.discordapp.com/attachments/692492808862302218/700955239146061914/image1.jpg
https://cdn.discordapp.com/attachments/692492808862302218/700955238181502976/image0.jpg

**Comment by davidcit646** [comment]
resolved in newest release
