### ISSUE TITLE
Base Protection script missing

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#25]
**Description:**
The anti-shooting/damage script in base doesn't work

**Steps to reproduce:**
Join server
Shoot guns in base

**Expected behavior:**
N/A

**Where did the issue occur?**
In-Game

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by Jaidendude** [comment]
[Could be related to this](https://github.com/7CavArma3Dev/7Cav-Alive-Altis/blob/52ffad9ad6640045a44b381382df4d462de93d61/onPlayerRespawn.sqf#L12)

**Comment by VinoEtCaseus** [comment]
I believe the repository itself is missing "scripts\greenZoneInit.sqf". The script gets ran in onPlayerRespawn.sqf which is ran locally. I don't believe it takes outside scripts so it can be taken directly from the previous tac2 repo. However, it should be noted it is kinda un-optimized and could use a rewrite (it was written before CBA3 was a thing).

**Comment by Jaidendude** [comment]
@davidcit646 This should be fixed along with the next update to altis
