### ISSUE TITLE
Vehicles Spawning and Freezing Above the Ground

### ISSUE THREAD

**Issue by mcurrier25** [7CavArma3Dev/7Cav-Alive-Altis#250]
**Description:**
In Chernarus the vehicles appear to be staying in mid-air when the map loads and do not touch down to the ground the way they should be.

**Steps to reproduce:**
- Go to ...
- Click ...
- See ...

**Expected behavior:**
Expected the vehicles to touch the ground upon the loading of map.

**Where did the issue occur?**
-  In-Game 

**Additional context:**
N/A

**Screenshots:**
Screenshots Provided
![IMG_1319](https://user-images.githubusercontent.com/62681812/79671392-f6454100-8197-11ea-9c53-c29a82bd0fd0.jpg)
![IMG_1317](https://user-images.githubusercontent.com/62681812/79671396-f8a79b00-8197-11ea-817e-305a0ed1e62b.jpg)
![IMG_1322](https://user-images.githubusercontent.com/62681812/79671398-fa715e80-8197-11ea-8fc5-e6aad9ef2555.jpg)

**Comment by davidcit646** [comment]
Issue related to the latest arma 3 update which affects physics. This will happen until RHS updates their mod.

Issue closed.
