### ISSUE TITLE
Chernarus v5.69 Slot Screen 

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#251]
**Description:**
List of slot changes needed in Chernarus (Autumn) v5.69
Apollo-1 to APOLLO-1
ALPHA2-5 to VIKING-1
ALPHA3-2 to BUFFALO-2

One extraneous slot may exist below the mission maker slot:
ALPHA4-5 (Combat Medic)

**Steps to reproduce:**
- Log onto Tac 2
- Check slot screen

**Expected behavior:**

**Where did the issue occur?**
- Lobby 

**Additional context:**

**Screenshots:**
![20200419140950_1](https://user-images.githubusercontent.com/61951971/79687786-fbfb5f00-8249-11ea-8c05-b98b81b0d2be.jpg)

**Comment by davidcit646** [comment]
Can we get a check on this on the latest update?

**Comment by davidcit646** [comment]
Fixed in latest release
