### ISSUE TITLE
ALiVE BLUFOR unit spawn faction

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#252]
**Description:**
It appears that in some mini-objectives that ALiVE spawns, it spawns some blufor to defend it. The current faction of units spawned is the default Nato 2035 troops.

If this is working as intended, please comment and disregard this issue.

**Steps to reproduce:**
- Log on
- Check mini-objectives spawns

**Expected behavior:**
Unsure if working as intended or is current US troops should be spawned (

**Where did the issue occur?**
- In-Game 

**Additional context:**
It might be too much of a headache to engineer a fix for this solution if it means additional faction calls, so this may be fine as is.

**Screenshots:**
![20200419144245_1](https://user-images.githubusercontent.com/61951971/79688222-1f73d900-824d-11ea-9af2-7919fafeed0f.jpg)
![20200419144259_1](https://user-images.githubusercontent.com/61951971/79688227-2995d780-824d-11ea-9b86-91732937623d.jpg)

**Comment by davidcit646** [comment]
This is set to Nato, because Nato is a default ALiVE faction. If players would like it changed, I would need to setup a default faction to change it to.

**Comment by Jaidendude** [comment]
I don't understand why we're still using C2ISTAR objectives, we all know they're buggy and don't work correctly.

**Comment by davidcit646** [comment]
Talk to S3 about that.
