### ISSUE TITLE
Chernarus V5.69 Base Air Defenses 

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#253]
**Description:**
The four Praetorian 1C turrets on the aircraft carrier are not manned/operational (lack ai)

The base is still defended by 2 Spartan and 1 Centurion turrets.

**Steps to reproduce:**
Check base turrets in Zeus

**Expected behavior:**
Turrets should have AI

**Where did the issue occur?**
- In-Game

**Additional context:**
I think the base is well defended even without the Praetorians. I tested it with some opfor aircraft, and they got closer than I expected but were shot down regardless.

If they are intended to be off, it may help to remove them from the map, which may help with the frames/stutter effect on base to reduce items.

**Screenshots:**
![20200419145637_1](https://user-images.githubusercontent.com/61951971/79688563-55b25800-824f-11ea-880b-f14183b4f5e1.jpg)

**Comment by davidcit646** [comment]
We disabled the cherno base defenses, as they were lighting up contacts in nearby towns. We thought it would be far easier to setup the missile defenses instead.

**Comment by BojanOnTheInternet** [comment]
Closing this as this is intentional.
