### ISSUE TITLE
SAHRANI - Mustang building doesn't have simulation

### ISSUE THREAD

**Issue by JoyfulJP** [7CavArma3Dev/7Cav-Alive-Altis#264]
**Description:**
Mustang has to teleport out of building; doors don't open. SAHRANI

NEED TO ADD SIMULATION TO BUILDING

**Comment by BojanOnTheInternet** [comment]
@JoyfulJP can you submit a pull request with this fix? Thanks

**Comment by davidcit646** [comment]
Fixed in beta
