### ISSUE TITLE
HAVOC Class not EOD Specialist

### ISSUE THREAD

**Issue by longlostblake** [7CavArma3Dev/7Cav-Alive-Altis#265]
**Description:**
Havoc are not EOD qualified (ACE Settings > is EOD [X]) on unit meaning explosives often blow up when defusing.

**Steps to reproduce:**
- Place down x number of AT mines
- Try to disable all of them 
- Fly into air as you fail

**Expected behavior:**
- Should be able to disarm 99% of all mines

**Where did the issue occur?**
- Sahrani, in Game

**Additional context:**
ACE Settings on squad members needs 'is EOD' tickbox checking.

**Screenshots:**

**Comment by BojanOnTheInternet** [comment]
What is the classname of the HAVOC units?

**Comment by longlostblake** [comment]
I haven't been able to replicate since. Maybe it was a wierd armaism. Please close.

**Comment by davidcit646** [comment]
won't fix/not our problem; issue closed
