### ISSUE TITLE
I can fortify as any role and also role perms are broken

### ISSUE THREAD

**Issue by BBPatten** [7CavArma3Dev/7Cav-Alive-Altis#281]
**Description:**
When loading into any role i an see the fortify money menu pop up on my screen even if im not Apollo. Also, perms are messed up with a lot of roles. Buffalo cannot enter their own aircraft and viking cannot enter any vehicles. Apollo are the only ones that can fly as of now alongside titan, sparrow, and raven
**Steps to reproduce:**
- Go to ... Tac2
- Click ... N/A
- See ... N/A

**Expected behavior:**
You will see the money menu pop up and also notice the roles messed up

**Where did the issue occur?**
In game and loading in

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by davidcit646** [comment]
vehicle permissions already mentioned; #270,  #274

**Comment by davidcit646** [comment]
fixed in next release
