### ISSUE TITLE
Sahrani base Defense reach

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#284]
**Description:**
Sahrani base AA defense engaged enemy armour on the hills south of the airfield at around 400m.

**Steps to reproduce:**
Spawn armour on hills south of base

**Expected behavior:**
Disregard if intended

**Where did the issue occur?**
In-Game

**Additional context:**
If not intended, not sure how this can be simply fixed, limiting FOV might hamper base defenses. Its just bad placement that there are hills overlooking the airfield.

**Screenshots:**

**Comment by DRAGONOFTRUTH-Strike** [comment]
Technically, base defenses defended the base no? 
I wonder if AA can be forced to only engage air threats and not ground vehicles

**Comment by Jaidendude** [comment]
I'd be glad armoured targets 400m from the base were being destroyed, that's well within kill range even for small arms fire

**Comment by OceanMan1125** [comment]
Sorry i forgot to update this, I double-checked the range as it seemed it was a bit small and its more like 1.4 kilometres from base.

Essentially targets on the hills south of the base are detectable and engaged by the AA defenses, at ranges of over kilometre and a half away and far from the base.

I also double checked and confirmed this behavior in another session

**Comment by davidcit646** [comment]
switched AA to SR missile defense; fixed in next update. Closed.
