### ISSUE TITLE
[Priority]Sahrani No-fire area

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#285]
**Description:**
Request from Tac 2 players to reduce no fire area to the East of the airfield. Specifically the the first gas station East South East of the airfield, where friendly forces are engaged from the nearby towns but cannot fire back.

**Steps to reproduce:**
- Go to gas station
- Attempt to fire back

**Expected behavior:**

**Where did the issue occur?**
In-Game

**Additional context:**

**Screenshots:**

**Comment by davidcit646** [comment]
Easy fix, takes 2 seconds to dial back.

**Comment by davidcit646** [comment]
fixed in latest release
