### ISSUE TITLE
[Priority] Base exit bar gate

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#286]
**What map is this feature request for?**
Any base with a bar gate exit

**Is your feature request related to a problem? Please describe.**
Most players don't take the time to get out and open any bar gate exits. They usually end up getting run over and don't look nice.

**Describe the solution you'd like**
Depending on the performance impact, we can make them open on a repeatable proximity trigger.

**Describe alternatives you've considered**
Removing the gates

**Additional context**
I have no idea what the long-term performance impact/residue of repeatable triggers is, and if it would hurt or be too much trouble to add one.

**Comment by davidcit646** [comment]
simple fix, ill implement this for sahrani for next release

**Comment by davidcit646** [comment]
fixed in latest release
