### ISSUE TITLE
[Duplicate] SABER Bradley Perms

### ISSUE THREAD

**Issue by OceanMan1125** [7CavArma3Dev/7Cav-Alive-Altis#287]
**Description:**
Report from public players that SABER slots cannot enter-drive the Bradley IFV.

**Steps to reproduce:**

**Expected behavior:**

**Where did the issue occur?**
In-Game Sahrani

**Additional context:**

**Screenshots:**

**Comment by davidcit646** [comment]
Duplicate Issue : #272

**Comment by davidcit646** [comment]
Issue fixed for next release; issue closed.
