### ISSUE TITLE
Sahrani - Vehicles Dont Work (TEST)

### ISSUE THREAD

**Issue by mazinskihenry** [7CavArma3Dev/7Cav-Alive-Altis#297]
**Map & Version**
Sahrani 5.8

**Description:**
You cannot enter vehicles on Sahrani

**Steps to reproduce:**
Tried to enter Sabre in Sabre slot
Told cannot enter Sabre

**Expected behavior:**
Slots should allow entry into corresponding vehicles

**Where did the issue occur?**
In-Game

**Comment by davidcit646** [comment]
fixed in 5.9

**Comment by davidcit646** [comment]
TEST DO NOT COMMENT
