### ISSUE TITLE
Tanoa air defenses dont work.

### ISSUE THREAD

**Issue by 7cavZlobinN** [7CavArma3Dev/7Cav-Alive-Altis#299]
**Map & Version**
Tanoa, 5.9rc1

**Description:**
Base defenses do not react to enemy air.

**Steps to reproduce:**
Spawn REDFOR mig-29S and set waypoint to base, and observe base turret behavior

**Expected behavior:**
Enemy air should be shot down when too close to base

**Where did the issue occur?**
In-game

**Comment by davidcit646** [comment]
Fixed in latest release.
