### ISSUE TITLE
Medic Slots don't have medic permissions

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#3]
**Description:**
Multiple users report medic permissions not functioning correctly

**Steps to reproduce:**
Join mustang slot, unable to stitch people unless near vehicle, would suggest slot is set to no perms, promoted to medic when near vehicle

**Expected behavior:**
Medics should be able to stitch themselves anywhere

**Where did the issue occur?**
- In-Game

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by davidcit646** [comment]
Working on it

**Comment by davidcit646** [comment]
This is a thing inside cScripts and I think that cScripts is assigning the wrong thing to the player character. This will be fixed when cScripts is updated.

**Comment by davidcit646** [comment]
Testing with this:
`medical_treatment,fullHealLocal`

**Comment by longlostblake** [comment]
This issue should be fixed with reccent pull request i made. I also increased the ammount of player damage taken as people were dying too quickly.
