### ISSUE TITLE
Takistan - Cannot spawn empty boxes

### ISSUE THREAD

**Issue by 7cavZlobinN** [7CavArma3Dev/7Cav-Alive-Altis#300]
**Map & Version**
Takistan 5.8

**Description:**
Logistics box spawner cannot spawn small and large crates.

**Steps to reproduce:**
Go to a logistics crate spawner and try to spawn a large or a small empty crate

**Expected behavior:**
An empty crate should spawn somewhere near the logistics pad

**Where did the issue occur?**
In-game

**Additional context:**
Issue is just with empty boxes, all of the other addactions work fine.

**Comment by davidcit646** [comment]
I think it could be a change of box classnames. I'll look into it. @BojanOnTheInternet Any input?

**Comment by Jaidendude** [comment]
Cannot spawn empty boxes on Sahrani either.

I did notice when i was doing my box spawner revamp that there isn't any empty boxes defined, so that might be it

**Comment by davidcit646** [comment]
Fixed in latest release.
