### ISSUE TITLE
Chernarus recon squad issues

### ISSUE THREAD

**Issue by longlostblake** [7CavArma3Dev/7Cav-Alive-Altis#303]
**Map**
Chernarus (unknown version)

**Description:**
1) Team member slot unable to access vehicles
2) group leader in editor is incorrect so callsign does not display.

**Steps to reproduce:**
- go to slot screen, notice wrong wrong group leader and incorrect callsign.
- select recon rifleman (maybe/probably others)
- try to enter a vehicle

**Expected behavior:**
Able to enter vehicle

**Where did the issue occur?**
- Lobby / In game

**Additional context:**
Vehicle restrictor script needs augmented i would assume

**Screenshots:**
N/a

**Comment by davidcit646** [comment]
Fixed in latest release.
