### ISSUE TITLE
Heavy Weapons Spawnable Box

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#304]
**What map is this feature request for?**
All currently in use

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A box spawnable through the logistics area at base, and through the APOLLO/ATLAS FOB Ammo Supply Container

This should contain one or multiple static weapon bags (Launcher bags, not backpack slot ones) and accompanying ammunition. This will allow mobile teams an easier way of getting SBF positions setup rapidly, and with the supplies to keep them running.

**Describe alternatives you've considered**
An alternative to a "generic heavy box" could be a spawnable box for each type (Mk. 19 Box / .50 HMG Box / 81mm Box) This box would have 1 or 2 of the specific heavy weapon type, but with more of the ammunition for that specific weapon. 

My suggestion for this:

2x .50cal HMGs per box 1000 rounds of ammo in 100 round boxes
1/2x Mk. 19s per box with 480 rounds of ammo in 48 round boxes
1x 81mm Mortar per box with a mix of rounds TBD out of a max of 20-30 rounds 
1x TOW per box with 10 rounds of ammo

**Additional context**

Edit: The boxes obviously would need to be loadable into vehicles, but not necessarily draggable, as efficient use of heavy static weapons requires 2 people (1 gunner, 1 assistant/ammo carrier)

**Comment by davidcit646** [comment]
Go into the ACE arsenal and get me the classnames. Write down the classnames in a comment and I'll see about adding a new box, each with a respective mk19, maaws, etc, to replace the generic boxes we have now.

I would like the MK19 and .50 cal classnames for each of the parts, meaning the tripod and gun, + the ammo.

Fomatting should look like this:
```
**MK19**
tripod_className
gun_className
ammo_className
```

**Comment by Jaidendude** [comment]
**.50cal HMG**
ace_csw_m3CarryTripodLow (Sitting version)
ace_csw_m3CarryTripod (Standing / AA vers, both should be included for flexibility)
ace_compat_rhs_usf3_m2_carry
ace_csw_100Rnd_127x99_mag_red (Red tracers)
ace_csw_100Rnd_127x99_mag (Ball)


**Mk. 19**
ace_csw_m3CarryTripodLow (only the low can be used with the mk19)
ace_compat_rhs_usf3_mk19_carry
ace_compat_rhs_usf3_48Rnd_40mm_MK19_M430A1


**TOW**
ace_csw_m220CarryTripod
ace_compat_rhs_usf3_tow_carry
ace_compat_rhs_usf3_mag_TOW2b (Many variants, but im including the most modern AT variant, and the anti-building bunker buster.)
ace_compat_rhs_usf3_mag_TOW2bb (Bunker buster)


**Stinger**
rhs_weap_fim92
rhs_fim92_mag


**FGM-148 Javelin**
rhs_weap_fgm148
rhs_fgm148_magazine_AT


**Barrett 50**
rhs_weap_M107
rhsusf_mag_10Rnd_STD_50BMG_mk211 (HE-API)
rhsusf_mag_10Rnd_STD_50BMG_M33 (Ball)


**240G**
rhs_weap_m240G
rhsusf_100Rnd_762x51_m80a1epr (EPR)
rhsusf_100Rnd_762x51_m61_ap (AP)

**Comment by davidcit646** [comment]
Investigating
