### ISSUE TITLE
Isla Duala unable to delete alive spawned enemies

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#325]
**Description:**
while in zeus, i am unable to delete any enemy NPC

**Steps to reproduce:**
- Go to zeus
- Click delete on enemy
- See nothing happen

**Expected behavior / Requested Solution:**
able to get rid of enemies that are clogging up server fps/ unknown

**Where did the issue occur?**
-zeus screen
**Additional context:**
none
**Screenshots:**
none

**Comment by 7cavZlobinN** [comment]
Needs to be an attribute change apparently

**Comment by davidcit646** [comment]
How where?

**Comment by 7cavZlobinN** [comment]
> 
> 
> How where?

going to discuss in pub missions chat on the discord

**Comment by davidcit646** [comment]
This is because of a known issue and is currently being worked on.

Closed due to duplicate issue #326 .
