### ISSUE TITLE
FPS is generally not very good

### ISSUE THREAD

**Issue by 7cavZlobinN** [7CavArma3Dev/7Cav-Alive-Altis#327]
**Map & Version**
Isla Duala 5.9

**Description:**
According to player reports, frames on isla duala are below average

**Steps to reproduce:**
Use zeus cam to activate a town or so of ALIVE enemies and observe FPS

**Expected behavior:**
Ideally frames are average to good unless literally the entire map of alive units is activated

**Where did the issue occur?**
in-game

**Additional context:**
Happens specifically on tac2 server, may not be able to test on dev2. Alive force size on isla duala is currently a company(200)

**Comment by davidcit646** [comment]
Fixed in latest release.
