### ISSUE TITLE
CLAfghan comms

### ISSUE THREAD

**Issue by 7cavZlobinN** [7CavArma3Dev/7Cav-Alive-Altis#329]
**Map & Version**
ClAfghan 5.9

**Description:**
Comms are impossible even over fairly short distances, to the point where it seems unrealistic.

**Steps to reproduce:**
Get your mate out on top of a mountain and try to talk to them from main base with a long range radio.

**Expected behavior:**
You should be able to communicate with forces halfway across the map from main base, regardless of terrain, with at least one type of man-portable radio.

**Where did the issue occur?**
In-game

**Comment by davidcit646** [comment]
Fixed in latest release.
