### ISSUE TITLE
Script Issue - Box spawner

### ISSUE THREAD

**Issue by LucanderP** [7CavArma3Dev/7Cav-Alive-Altis#337]
**Map & Version**
CLA Clafghan v 5.9

**Description:**
Script bug on Box spawner.

**Steps to reproduce:**
- Go to Box spawner on any of the new missions.
- Scroll on the box spawner.
- You will see two alternetives, where there should be seven and the two alternatives are not currently working. (as of 2020-06-18 23:00z)

**Expected behavior:**
Should spawn boxes with medical and ammo.

**Where did the issue occur?**
- In-Game

**Additional context:**

**Screenshots:**
![107410_screenshots_20200619072545_1](https://user-images.githubusercontent.com/66979447/85099714-70c52800-b1fe-11ea-8eb9-4fee9f36c0ad.jpg)

**Comment by LucanderP** [comment]
all v 5.9 missions seem to have the script issue.

**Comment by Jaidendude** [comment]
When I posted the changelog for this issue I already stated that this is a known issue and is already fixed and ready to be released along with the next hotfix.

https://i.gyazo.com/e8402c58782212f3be495c92c8bd1073.png
