### ISSUE TITLE
Spawn / Teleport Issue - Logistics Personnel Module

### ISSUE THREAD

**Issue by LucanderP** [7CavArma3Dev/7Cav-Alive-Altis#338]
**Map & Version**
v 5.9

**Description:**
We are having trubbel with respawning on and teleporting to the Logistics Personnel Module.

**Steps to reproduce:**
opened it up outside of the base near the fob truck.
could not spawn on it.
did not find any vics that have the teleport script.

**Expected behavior:**
Should be able to spawn on it or teleport to it.

**Where did the issue occur?**
In-Game

**Additional context:**

**Screenshots:**

**Comment by Jaidendude** [comment]
What map is this issue present on?

**Comment by 7cavZlobinN** [comment]
Assuming this is on Lingor because we overlooked placing the teleporter APC. Fixed with #333 and will be released whenever the next patch gets out.

**Comment by LucanderP** [comment]
most of the new maps. i don't have admin on Tac 2 so i cant check all for sure.
