### ISSUE TITLE
Database issue - Tac2 7Cav Loyalty Rewards

### ISSUE THREAD

**Issue by LucanderP** [7CavArma3Dev/7Cav-Alive-Altis#340]
**Map & Version**
v 5.9

**Description:**
new points and ranks are not getting saved. old points and ranks are not showing up.

**Steps to reproduce:**
- go up to the guy in the 7Cav Loyalty Rewards box
- scroll on him (he might be hiding)
- use the "Loyalty Vehicle Selector". 
- leave session and comeback in and repeat.

**Expected behavior:**
points and ranks should save from session to session.

**Where did the issue occur?**
In-Game

**Additional context:**

**Screenshots:**

**Comment by 7cavZlobinN** [comment]
Known issue. Bojan and Sweetwater should be working on it.

**Comment by LucanderP** [comment]
okay, just posting as i haven't seen a post on it.
