### ISSUE TITLE
Adding some more manual drive vehicles

### ISSUE THREAD

**Issue by LucanderP** [7CavArma3Dev/7Cav-Alive-Altis#344]
**What map is this feature request for?**
all maps  (Found it not implemented on Lingor Island so far)

**Is your feature request related to a problem? Please describe.**
I would like to use the gun and drive at the same time.

**Describe the solution you'd like**
Adding M1A2SEPv1(TUSK II), M2A3 (BUSK III), M6A2, M1134, M1126 (M2), M1126 (Mk 19) and M1127 (M2/LRAS3) to the list of manual drive vehicles.

**Describe alternatives you've considered**

**Additional context**

**Comment by 7cavZlobinN** [comment]
All stryker variants have manual drive as of 5.9, verified myself. Them not having manual drive may be a separate bug that inconsistently occurs.

Current classes that have manual drive.

```// Armored vehicles
TypeFilter_ArmoredVehicles =
[
	["MBT_03_base_F", true], // Leopard 2
	["MBT_01_base_F", true], // Most other western tanks (Abrams, Merkava)
	["RHS_M2A3*", true], // Add Bradleys here too so Manual Drive works for all
	["B_AFV_Wheeled_01*", true], // Rookiat tank destoryer
	["B_APC_Wheeled_01*", true],
	["rhsusf_stryker*", true],
	["I_LT_01*", true],
	["All", false]
];```

**Comment by LucanderP** [comment]
can you check that the woodland versions are added too?

**Comment by 7cavZlobinN** [comment]
Can confirm that every armored vehicle you listed except for the M6A2 and M113 have manual drive on Lingor. These appear to be omissions and I will open a separate issue to add them in the next patch.

**Comment by LucanderP** [comment]
okay, works now, thanks.
