### ISSUE TITLE
Anyone can get in pilot seats

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#35]
**Description:**
Anyone can get into any aircraft seat

**Steps to reproduce:**
Join server and go into any slot, you can get into any aircraft

**Expected behavior:**
Infantry slots should not be able to get into aircraft pilot seats

**Where did the issue occur?**
- In-Game

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by davidcit646** [comment]
This is a direct result of not having vehicle permissions in place.

**Comment by Jaidendude** [comment]
Related to #58

**Comment by BojanOnTheInternet** [comment]
Fixed along with #58
