### ISSUE TITLE
Apollo fortify issues

### ISSUE THREAD

**Issue by benidem** [7CavArma3Dev/7Cav-Alive-Altis#351]
Map & Version
Tanoa 5.9.2

Description:
Apollo fortify option costs twice and much as shown in the menu and if you right click to cancel building something it does not refund you the money. If you try to build something and cannot pay the secret double cost it will simple deduct the normal cost. If you have $270 and try to build a field hospital for $150 it won't even give you the ghost of the hospital to place just deduct $150 from your budget leaving you $120.

Steps to reproduce:
Pick an Apollo slot and use the fortify tool
Build things
Watch too much money do down
Try cancelling a build
watch your money not go back up

Expected behavior:

Where did the issue occur?
In game

Additional context:
SPC.Robinson.W feel free to ask me questions on TS

Screenshots:

**Comment by 7cavZlobinN** [comment]
Unable to reproduce
