### ISSUE TITLE
Apollo Builder, Bring back the bridge please.

### ISSUE THREAD

**Issue by LucanderP** [7CavArma3Dev/7Cav-Alive-Altis#352]
**What map is this feature request for?**
-

**Is your feature request related to a problem? Please describe.**
need a bridge in the builder.

**Describe the solution you'd like**
cant build a proper bridge with the new pontoon plate, its not working in the builder properly, so i cant make a proper ramp that wont kill players driving low vehicles.

**Describe alternatives you've considered**
Bring back the bridge.

**Additional context**

**Comment by LucanderP** [comment]
![107410_screenshots_20200701023826_1](https://user-images.githubusercontent.com/66979447/86190369-7dbe1180-bb44-11ea-88d2-03be6018bb58.jpg)

**Comment by LucanderP** [comment]
![107410_screenshots_20200701024152_1](https://user-images.githubusercontent.com/66979447/86190472-b958db80-bb44-11ea-8ad9-20bcc53bb8a7.jpg)

**Comment by 7cavZlobinN** [comment]
Roger, I have this fixed in the next update and will close this once the pull request goes through. Im shifting things around in the build list and Apollo will have access to both the pontoons and the original wooden bridges.

**Comment by LucanderP** [comment]
Thanks
