### ISSUE TITLE
Tanoa Infantry Respawn

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#355]
**Description:**
A clear and concise description of what the problem is.
When re-spawning at the infantry spawn point of the Tanoa map it spawns you on top of the building.
**Steps to reproduce:**
- Go to ... Tanoa
- Click ...Escape, press respawn, select the infantry spawn location and click spawn.
- See ...You will find yourself on the roof.

**Expected behavior / Requested Solution:**
A clear and concise description of what you expected to happen. (Or if it's a feature request, what you propose to satisfy the issue.)
Not a major issue, just a small pain in the butt to have to climb down off the building would be nice to spawn inside the building itself.
**Where did the issue occur?**
- Lobby / Map-Screen / In-Game / Other
In-Game
**Additional context:**

**Screenshots:**

**Comment by 7cavZlobinN** [comment]
Will be fixed in the next patch
