### ISSUE TITLE
Loyalty points

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#356]
**Description:**
I was wondering if loyalty points thing could be improved, currently the grind for points is pretty long with the only way to get points is every 15 minutes you are on the server.(I do think it should be a somewhat long grind however.) I was thinking what if you could also earn points from completing objectives and getting kills. For example you might get 1 point per infantry kill, 5 for destroying cars and trucks, 10 for tanks and aircraft. Completing a minor/major objective could be 10-50/50-100. I think this would make a great addition to the server and might give players a bit of a rewarding feeling for playing.

**Comment by LucanderP** [comment]
i think this is a great idea, as getting levels is really boring currently and not a rewarding experience.

**Comment by NikPoliakov** [comment]
Loyalty points system is being removed and replaced with a regular vehicle spawner. 
Closing this.
