### ISSUE TITLE
Clafgan slot permissions

### ISSUE THREAD

**Issue by drw13rd** [7CavArma3Dev/7Cav-Alive-Altis#357]
**Map & Version**
Clafgan

**Description:**
Havoc ar slot lacks permissions for riding in any helicopter passenger slot

**Steps to reproduce:**
slot as havoc ar
try to get in spawned buffalo

**Expected behavior:**
getting in the buffalo

**Where did the issue occur?**
in-game

**Additional context:**
n/a

**Screenshots:**
n/a

**Comment by 7cavZlobinN** [comment]
Issue has been found and will be fixed in the next patch
