### ISSUE TITLE
Lingor H.E.M.M.Ts missing

### ISSUE THREAD

**Issue by drw13rd** [7CavArma3Dev/7Cav-Alive-Altis#362]
**Map & Version**
Lingor

**Description:**
Lack of refuel, repair, and ammo H.E.M.M.Ts on base for non fixed wing vehicles

**Steps to reproduce:**
n/a

**Expected behavior:**
Facilities to maintain vehicle assets when apollo vics are not in base

**Where did the issue occur?**
in-game

**Additional context:**
n/a

**Screenshots:**
n/a

**Comment by 7cavZlobinN** [comment]
Known issue, fixed in next patch.
