### ISSUE TITLE
Medical permissions not working for Mustang

### ISSUE THREAD

**Issue by 7cavZlobinN** [7CavArma3Dev/7Cav-Alive-Altis#367]
**Map & Version**
5.9.4 all maps

**Description:**
Mustang cannot PAK, but Apollo can

**Comment by NikPoliakov** [comment]
Mustang now has doctor perms.
Apollo now only has advanced engineering.

**Comment by NikPoliakov** [comment]
Fixed doctor perms for Mustang.
Removed doctor perms from apollo, it now has advanced engineering only.
