### ISSUE TITLE
cScripts Update

### ISSUE THREAD

**Issue by 7cavZlobinN** [7CavArma3Dev/7Cav-Alive-Altis#370]
Tasking: Update tac2 cScripts to the latest public cScripts version

READ INSTRUCTIONS IN FULL BEFORE STARTING

Step 1. Download cScripts_PUBLIC-4.3.26.zip from https://github.com/7Cav/cScripts/releases/tag/4.3.26

Step 2. Create a new branch off of dev branch named "cScripts Update" and make it the active branch

Step 3. Navigate to your local copy of 7Cav-Alive.Altis

Step 4. Copy the folder named "cScripts" from the copy of cScripts you just downloaded, and paste it into the Altis mission folder

Step 5. Over-write every file EXCEPT initFortify.sqf

Step 6. in CfgLoadouts.hpp add to the CfgLoadouts class: 
`// Tac2 `
`#include "Loadouts\CfgLoadouts_tac2.hpp" `
`   #include "Loadouts\CfgLoadouts_tac2Class.hpp"`

Report back to zlobin with the mission folder when complete for testing

**Comment by NikPoliakov** [comment]
I already pushed DEV version of cscripts.
