### ISSUE TITLE
ALiVE not spawning enough enemies

### ISSUE THREAD

**Issue by davidcit646** [7CavArma3Dev/7Cav-Alive-Altis#39]
**Description:**
The AOs arent hard enough due to lack of spawning

**Steps to reproduce:**
- Small priority towns

**Expected behavior:**
3-4 squads expected per townl

**Solution**
Bump spawning to 150 for infantry, 50-100 for mech, 50-100 for motor

**Comment by davidcit646** [comment]
Will be done tonight

**Comment by Jaidendude** [comment]
@davidcit646 @BojanOnTheInternet Might want to re-consider this.
