### ISSUE TITLE
F35 can launch a nuke

### ISSUE THREAD

**Issue by davidcit646** [7CavArma3Dev/7Cav-Alive-Altis#40]
**Description:**
The f35 has access to a nuke

**Expected behavior:**
Option 1: Remove until further notice
Option 2: Contact raynor for scripting help

**Screenshots:**
https://cdn.discordapp.com/attachments/657354249075687428/662841187702538270/image0.jpg

**Comment by RaynorD** [comment]
I'll add a CBA setting to disable the nuclear script, just make it a big bomb. We have an update close to being ready and I'll make sure it makes it in.

**Comment by davidcit646** [comment]
Awesome! We'll check that as soon as you release it!

**Comment by davidcit646** [comment]
Elevated to high priority, as the F35 is a crowd favorite!

**Comment by Jaidendude** [comment]
RaynorD Already said this is a non-mission issue and will issue a fix in the next USAF Update.

**Comment by davidcit646** [comment]
re-added f35 and confuigured CBA_Settings. Adding additional issue for tracking.
