### ISSUE TITLE
AI occupying a small number of houses in towns

### ISSUE THREAD

**Issue by davidcit646** [7CavArma3Dev/7Cav-Alive-Altis#46]
**Description:**
AI will only take about a house or two for themselves out of a town of 25-40 houses.

**Steps to reproduce:**
- Go to neochori
- AI only in two houses

**Expected behavior:**
numerous houses occupied in a given town

**Where did the issue occur?**
- In-Game

**Comment by Jaidendude** [comment]
Probably related to #39
