### ISSUE TITLE
ALiVE garbage cleanup doesn't work

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#68]
**Description:**
ALiVE Cleanup doesn't appear to cleanup units and other things

**Steps to reproduce:**
- Join server
- Die
- Body isn't removed

**Expected behavior:**
Cleanup should work after 300 seconds

**Where did the issue occur?**
- In-Game

**Additional context:**
N/A

**Screenshots:**
N/A

**Comment by davidcit646** [comment]
confirmed working
