### ISSUE TITLE
New USAF aircraft not added to vehicle permissions

### ISSUE THREAD

**Issue by TsinS** [7CavArma3Dev/7Cav-Alive-Altis#74]
**Description:**
Logging in as Hog or Eagle pilot doesn't allow you to get into the pre-spawned A10 or F-22.

**Steps to reproduce:**
Select Hog or Eagle pilot role.
Attempt to get into A10 or F22.
Cannot get in.

**Where did the issue occur?**
In-game

**Additional context:**
If I spawn a A10 for the pilot, they can get in.

Also, I've had buffalo and raven pilots not able to get into their birds. And they can't get in even if I spawn the birds.

**Screenshots:**

**Comment by Jaidendude** [comment]
@TsinS Please edit your issue to follow the issue reporting template.

**Comment by TsinS** [comment]
Fixed, sorry!

**Comment by Jaidendude** [comment]
@BojanOnTheInternet Issue probably related to #58 #35

**Comment by BojanOnTheInternet** [comment]
Fixed in 99079473f94038d97e9256dd39fdfb056bb87ac6
