### ISSUE TITLE
ACE NVG settings result in poor vision

### ISSUE THREAD

**Issue by TsinS** [7CavArma3Dev/7Cav-Alive-Altis#75]
(FIXED, sorry!)

**Description:**
The old extremely grainy night vision is back. Can't see anything in dead of night. Please adjust the night vision settings.

**Steps to reproduce:**
Turn on night vision in the dead of night.

**Expected behavior:**
Our previous modified version of night vision.

**Where did the issue occur?**
In-game.

**Additional context:**
Night vision grainy vision DOES NOT occur when using the night vision in Zeus mode.

**Screenshots:**
(did not obtain)

**Comment by Jaidendude** [comment]
@TsinS Please edit your issue to follow the issue reporting template.

**Comment by TsinS** [comment]
fixed template, sorry!
