### ISSUE TITLE
Zeus Camera Spawns AI

### ISSUE THREAD

**Issue by Prototype9x** [7CavArma3Dev/7Cav-Alive-Altis#79]
**Description:**
Zeus Camera is recognized as a player. Zeus Camera triggers AI to spawn anywhere it moves on the map

**Steps to reproduce:**
- Go to Map in Zeus
- Click Middle Mouse Button to move Zeus Camera anywhere on map
- See AI spawning within 1km of Zeus Camera position

**Expected behavior:**
Zeus Camera should not spawn AI

**Where did the issue occur?**
- In-Game

**Additional context:**
Zeus Camera spawns in EXTRA AI at times when moved on top of players in contact

**Screenshots:**
N/A

**Comment by Jaidendude** [comment]
@Prototype9x The Zeus camera is designed to spawn in AI around a radius of the camera's location, so the curator can give tactical orders to enhance gameplay. This is something built into ALiVE to provide flexibility to active curators.

If you'd like to avoid spawning extra enemies, keep the camera centered on top of players as closely as possible. 

Any 'extra' enemies spawning, in towns most likely, is the CQB module providing extra contacts inside houses, the new 5.1.0 update should address many problems, including overwhelming AI count.
