### ISSUE TITLE
Occupy and Hold Objectives

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#91]
**Description:**
Mission progression comes to a halt on Occupy and Hold Objectives. Players can't always find all of the attacking forces to eliminate. Operational momentum slows way down, and eventually server population drops off.

**Steps to reproduce:**
Occupy and hold is assigned.

**Expected behavior / Requested Solution:**
It is unknown to many players if this objective is timed, % of attackers destroyed, or all attacking forces are eliminated. Players have tried using several drones, helicopters, and patrols to find enemy. If it is a "Hold" mission the enemy should be the aggressor, and it shouldn't require three hours of game time to find a couple of enemy ei that wondered away.

**Where did the issue occur?**
- In-Game

**Additional context:**
Listing this as an enhancement because it may be working as intended, but it hinders overall experience.

**Screenshots:**

**Comment by Jaidendude** [comment]
Related to auto-generated missions, which are buggy AF anyway. Really shouldn't be used much at all, unsure if CSISTAR's mission generation is still turned on, and IMO it should be turned off. @davidcit646

**Comment by davidcit646** [comment]
Interesting problem. Task generation is the bane of my existence right now. We've had so many problems with it. I can see what I can do. To the original poster, did someone hop into zeus to check if there were any AI anywhere in the objective area?

**Comment by 7CavDread** [comment]
A zeus created the task, or so I assume he did. After we struggled a bit locating enemy the zeus then logged off. It feels as though the zeus's are struggling with the mission file a bit as they learn what works and doesn't. I have got very little input from a lot of the S3 zeus on how the map is supposed to operate. Big learning curve to very cool map.
