### ISSUE TITLE
Apollo Arsenal Crate

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#95]
**Description:**
Apollo arsenal crates have no ACE arsenal attached.

**Steps to reproduce:**
Slot in as Apollo team leader, walk to Apollo arsenal crates and ace interact

**Expected behavior / Requested Solution:**
Apollo needs these crates to conveniently supply their vehicles, and so adding the arsenal back in is very much needed.

**Comment by Mecaguy03** [comment]
Bit of context I forgot to add, this is on the Altis mission file.
