### ISSUE TITLE
Apollo fortification building

### ISSUE THREAD

**Issue by Jaidendude** [7CavArma3Dev/7Cav-Alive-Altis#96]
**Description:**
Apollo cannot place fortifications when near the m1084A1R SOV (m2)

**Steps to reproduce:**
Slot in as Apollo Team Leader
Get loadout with fortify tool and toolkit in backpack
Move m108 SOV outside of blue zone on base
ACE self interact

**Expected behavior / Requested Solution:**
Previously when within range of the M108 SOV Apollo would get the ace option to place fortifications.

**Where did the issue occur?**
In-game on 7cav_FullSpectrum_v5.1.2 on Altis

**Comment by Mecaguy03** [comment]
As of today this is still an issue.

**Comment by Jaidendude** [comment]
@davidcit646 has this been fixed yet?

**Comment by davidcit646** [comment]
Elevated priority. This is next on the list.

**Comment by 7cavZlobinN** [comment]
Fixed #153
