### ISSUE TITLE
Unable to PAK at hospital 

### ISSUE THREAD

**Issue by longlostblake** [7CavArma3Dev/7Cav-Alive-Altis#97]
**Description:**
Unable to PAK at hospital building on base

**Steps to reproduce:**
Go to a medical facility as Mustang
Attempt to PAK inside

**Expected behavior:**
Should Be able to PAK

**Where did the issue occur?**
Tact-2 on Base

**Additional context:**
Building probably not set as medical facility or CBA setting is wrong.

**Screenshots:**

**Comment by Jaidendude** [comment]
@longlostblake Was the patient conscious?

**Comment by Jaidendude** [comment]
Investigated, doesn't seem like a valid issue
